name: Build
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "9.2"
          - "9.4"
          - "9.6"
          - "9.8"
          - "9.10"
        include:
          - os: macOS-latest
            ghc: "9.10"
          - os: windows-latest
            ghc: "9.10"
    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"
        cabal-update: true

    - uses: actions/cache@v4
      name: Cache cabal store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Cabal version
      run: |
        cabal --version

    - name: Install doctest
      run: |
        mkdir -p "${{github.workspace}}/doctest-bin"
        cabal install --install-method=symlink --installdir "${{github.workspace}}/doctest-bin" doctest

    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get prettyprinter-combinators-*.tar.gz

    - name: Build default
      run: |
        cd ../prettyprinter-combinators-*/
        cabal build all --enable-tests --enable-benchmarks --flags="+enummapset"

    - name: Build without enummapset
      run: |
        cd ../prettyprinter-combinators-*/
        cabal build all --enable-tests --enable-benchmarks --flags="-enummapset"

    - name: Doctest
      run: |
        cd ../prettyprinter-combinators-*/
        cabal repl --with-ghc "${{github.workspace}}/doctest-bin/doctest" --repl-options=-Wno-missing-export-lists 'lib:prettyprinter-combinators'

    - name: Haddock
      run: |
        cd ../prettyprinter-combinators-*/
        cabal haddock all

    - name: Cabal check
      run: |
        cd ../prettyprinter-combinators-*/
        cabal check
